services:
  app:
    build: .
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:password@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: